name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Change to website directory
      run: cd website
    
    - name: Install dependencies
      run: |
        cd website
        yarn install --frozen-lockfile
    
    - name: Build Angular app
      run: |
        cd website
        yarn build
    
    - name: Prepare deployment files
      run: |
        cd website
        # Copy EN version files to root for static assets
        cp -r ./dist/vcg-website/browser/en/* ./dist/vcg-website/browser/
        # Remove duplicate en folder to avoid confusion
        rm -rf ./dist/vcg-website/browser/en/en
        rm -rf ./dist/vcg-website/browser/en/fr
    
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./website/dist/vcg-website/browser/
        server-dir: ./public_html/
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .htaccess
          .well-known/**
          cgi-bin/**